### ISSUE TITLE
Follow-up Regarding our Conversation about Landmark-based TSM

### ISSUE THREAD

**Issue by salavina** [CvHadesSun/RepNet#1]
Hi Hades,

Thank you so much for your detailed explanation in the email! I have a few follow-up questions (that may seem dumb to you haha). 

You mentioned 7x3=21 features per frame based on landmarks, I was wondering what do numbers 3 and 7 represent? Also, how would I obtain 64 frames out of let's say 1600 frames the video has to create (64x21) features? do I randomly pick frames with equal distance or is there a defined method for this?

Thanks!

**Comment by CvHadesSun** [comment]
@salavina ,
For per 2D-landmark,if you have per landmark confidence score, there is 3-dims for each landmark, if not, only x-axis and y-axis (2-dims) are just ok, then your feature tensor shape is 7x2. And 64 frames's TSM is repnet's one input, that means, in the 64 frames , the repnet can count the number of excise cycle, and next, you should input time-next 64 frames into repnet. So, if you have 1600 frames, you just arrange n=1600/64 times input to the repnet, and for the output of the each input , you can get the results in this 64 frames input, and so on.
Good luck.
