### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by oo92** [CvHadesSun/RepNet#2]
Where is `'../data/aff_matrix.npy'`?

**Comment by CvHadesSun** [comment]
@oo92  sorry so late to reply to you, this is a similarity matrix, you need to construct it according to your data by yourself. Maybe you can get some detail from [here] (https://github.com/CvHadesSun/RepNet/issues/1). And in the code, this matrix is generated from the feature extract network, and you can save it by yourself. and you should run this demo normally with the current source code.
